<a href="https://colab.research.google.com/github/lizzylazy/NLP_pytorch/blob/main/Chapter1pytorch_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Connecting google drive

In [2]:
from google.colab import drive
drive.mount('/content/gdrive')


Mounted at /content/gdrive


In [3]:
% cd /content/gdrive/MyDrive/pytorch_NLP/

/content/gdrive/MyDrive/pytorch_NLP


In [4]:
%ls 

Chapter1pytorch_intro.ipynb


In [5]:
pwd

'/content/gdrive/MyDrive/pytorch_NLP'

# Create a tensor

In [6]:
import torch

In [7]:
# help function 
def describe(x):
  print('Type:{}'.format(x.type()))
  print('Shape/Size: {}'.format(x.shape))
  print('Value: \n{}'.format(x))

In [8]:
describe(torch.Tensor(2,3))

Type:torch.FloatTensor
Shape/Size: torch.Size([2, 3])
Value: 
tensor([[-2.2189e+20,  3.0792e-41,  3.7835e-44],
        [ 0.0000e+00,         nan,  3.0792e-41]])


In [9]:
describe(torch.rand(2,3))
describe(torch.randn(2,3))

Type:torch.FloatTensor
Shape/Size: torch.Size([2, 3])
Value: 
tensor([[0.4533, 0.9392, 0.3330],
        [0.9863, 0.0221, 0.5340]])
Type:torch.FloatTensor
Shape/Size: torch.Size([2, 3])
Value: 
tensor([[-0.6916, -0.2157, -0.4908],
        [ 3.0094,  1.3148,  0.7771]])


In [10]:
describe(torch.zeros(2,3))
describe(torch.ones(2,3))

Type:torch.FloatTensor
Shape/Size: torch.Size([2, 3])
Value: 
tensor([[0., 0., 0.],
        [0., 0., 0.]])
Type:torch.FloatTensor
Shape/Size: torch.Size([2, 3])
Value: 
tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [11]:
x = torch.arange(6, dtype=float)

In [12]:
describe(x)

Type:torch.DoubleTensor
Shape/Size: torch.Size([6])
Value: 
tensor([0., 1., 2., 3., 4., 5.], dtype=torch.float64)


In [17]:
x = x.reshape(2,3) # reshape and view have the same results
describe(x)

Type:torch.DoubleTensor
Shape/Size: torch.Size([2, 3])
Value: 
tensor([[0., 1., 2.],
        [3., 4., 5.]], dtype=torch.float64)


In [18]:
describe(x.sum())
describe(x.sum(dim=0)) # sum along row
describe(x.sum(dim=1)) # sum along column

Type:torch.DoubleTensor
Shape/Size: torch.Size([])
Value: 
15.0
Type:torch.DoubleTensor
Shape/Size: torch.Size([3])
Value: 
tensor([3., 5., 7.], dtype=torch.float64)
Type:torch.DoubleTensor
Shape/Size: torch.Size([2])
Value: 
tensor([ 3., 12.], dtype=torch.float64)


In [19]:
describe(x.transpose(1,0))
describe(x.transpose(0,1))

Type:torch.DoubleTensor
Shape/Size: torch.Size([3, 2])
Value: 
tensor([[0., 3.],
        [1., 4.],
        [2., 5.]], dtype=torch.float64)
Type:torch.DoubleTensor
Shape/Size: torch.Size([3, 2])
Value: 
tensor([[0., 3.],
        [1., 4.],
        [2., 5.]], dtype=torch.float64)


In [20]:
row_indices = torch.arange(2).long()
col_indices = torch.LongTensor([0, 1])
# describe(x[row_indices, col_indices])

In [21]:
row_indices

tensor([0, 1])

In [22]:
col_indices

tensor([0, 1])

In [23]:
x[row_indices, col_indices]

tensor([0., 4.], dtype=torch.float64)

# Tensors and Computational Graphs


In [24]:
import torch
x = torch.ones(2, 2, requires_grad=True)
describe(x)
print(x.grad is None)

Type:torch.FloatTensor
Shape/Size: torch.Size([2, 2])
Value: 
tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
True


In [25]:
y = (x + 2) * (x + 5) + 3
describe(y)
print(x.grad is None)

Type:torch.FloatTensor
Shape/Size: torch.Size([2, 2])
Value: 
tensor([[21., 21.],
        [21., 21.]], grad_fn=<AddBackward0>)
True


In [26]:
z = y.mean()
describe(z)
z.backward()
print(x.grad is None)

Type:torch.FloatTensor
Shape/Size: torch.Size([])
Value: 
21.0
False


# Exercises

1. Create a 2D tensor and then add a dimension of size 1 inserted at dimension 0

In [27]:
x = torch.arange(6).view(2,3)
describe(x)

Type:torch.LongTensor
Shape/Size: torch.Size([2, 3])
Value: 
tensor([[0, 1, 2],
        [3, 4, 5]])


In [28]:
y = x.unsqueeze(0) # add a dimension at dimendion 0

Type:torch.LongTensor
Shape/Size: torch.Size([1, 2, 3])
Value: 
tensor([[[0, 1, 2],
         [3, 4, 5]]])


In [29]:
y = x.unsqueeze(2) # add a dimension at dimendion 2
describe(y)

Type:torch.LongTensor
Shape/Size: torch.Size([2, 3, 1])
Value: 
tensor([[[0],
         [1],
         [2]],

        [[3],
         [4],
         [5]]])


2. Remove the extra dimension you just added to the previous tensor.


In [32]:
b = y.squeeze(2) # delete the added the dimension at dimendion 2
describe(b)

Type:torch.LongTensor
Shape/Size: torch.Size([2, 3])
Value: 
tensor([[0, 1, 2],
        [3, 4, 5]])


3. Create a random tensor of shape 5x3 in the interval [3, 7)

In [33]:
a = torch.rand(5,3)
z= 3+a * 4

In [34]:
describe(z)

Type:torch.FloatTensor
Shape/Size: torch.Size([5, 3])
Value: 
tensor([[6.9314, 4.2247, 4.9379],
        [4.4607, 6.0720, 5.2231],
        [6.5747, 3.5883, 3.8294],
        [4.4579, 3.0266, 4.7698],
        [5.4972, 4.3908, 6.0613]])


4. Create a tensor with values from a normal distribution (mean=0, std=1).


In [37]:
torch.randn(2,3) # random normal distribution tensor with size (2,3)


tensor([[-0.4168, -2.7415,  1.3455],
        [ 0.3175, -0.0065, -0.4627]])

5. Retrieve the indexes of all the nonzero elements in the tensor torch.Tensor([1, 1, 1,
0, 1])

In [46]:
x = torch.tensor([1,1,1,0,1])

In [47]:
idx = torch.nonzero(x)
idx

tensor([[0],
        [1],
        [2],
        [4]])

6. Create a random tensor of size (3,1) and then horizontally stack four copies together

In [55]:
x = torch.rand(3,1)
y = torch.stack((x, x,x,x), dim=1).squeeze(2)
describe(x)
describe(y)

Type:torch.FloatTensor
Shape/Size: torch.Size([3, 1])
Value: 
tensor([[0.6377],
        [0.7674],
        [0.7647]])
Type:torch.FloatTensor
Shape/Size: torch.Size([3, 4])
Value: 
tensor([[0.6377, 0.6377, 0.6377, 0.6377],
        [0.7674, 0.7674, 0.7674, 0.7674],
        [0.7647, 0.7647, 0.7647, 0.7647]])


In [54]:
x = torch.rand(3,1)
y = x.expand(3,4)
describe(x)
describe(y)

Type:torch.FloatTensor
Shape/Size: torch.Size([3, 1])
Value: 
tensor([[0.6713],
        [0.4560],
        [0.9552]])
Type:torch.FloatTensor
Shape/Size: torch.Size([3, 4])
Value: 
tensor([[0.6713, 0.6713, 0.6713, 0.6713],
        [0.4560, 0.4560, 0.4560, 0.4560],
        [0.9552, 0.9552, 0.9552, 0.9552]])


7. Return the batch matrix­matrix product of two three­dimensional matrices
(a=torch.rand(3,4,5), b=torch.rand(3,5,4)).

In [38]:
a=torch.rand(3,4,5)
b=torch.rand(3,5,4)
c = torch.bmm(a,b)
describe(c)

Type:torch.FloatTensor
Shape/Size: torch.Size([3, 4, 4])
Value: 
tensor([[[1.0356, 1.3230, 1.4704, 2.3555],
         [1.2645, 1.3723, 2.0659, 2.4643],
         [0.6828, 1.0022, 1.3347, 1.5519],
         [1.1898, 1.2609, 1.8548, 2.0926]],

        [[1.0221, 1.0521, 0.8851, 0.8829],
         [0.9126, 0.8000, 0.6823, 0.8128],
         [0.8739, 1.1457, 0.8259, 0.7038],
         [1.3348, 1.3943, 0.8922, 0.8217]],

        [[1.2477, 0.9949, 0.6458, 1.8536],
         [1.3285, 0.6793, 0.8304, 1.5074],
         [0.9878, 0.9399, 0.6733, 1.6997],
         [1.3922, 0.8752, 0.7922, 1.7901]]])


8. Return the batch matrix­matrix product of a 3D matrix and a 2D matrix
(a=torch.rand(3,4,5), b=torch.rand(5,4))

In [39]:
a=torch.rand(3,4,5)
b=torch.rand(5,4)

In [41]:
c = b.unsqueeze(0).expand(a.size(0), *b.size())
describe(c)

Type:torch.FloatTensor
Shape/Size: torch.Size([3, 5, 4])
Value: 
tensor([[[0.1463, 0.3807, 0.6052, 0.4311],
         [0.4888, 0.7776, 0.6835, 0.5198],
         [0.3531, 0.5815, 0.3338, 0.6531],
         [0.1442, 0.9355, 0.8658, 0.2634],
         [0.2609, 0.6348, 0.1194, 0.8101]],

        [[0.1463, 0.3807, 0.6052, 0.4311],
         [0.4888, 0.7776, 0.6835, 0.5198],
         [0.3531, 0.5815, 0.3338, 0.6531],
         [0.1442, 0.9355, 0.8658, 0.2634],
         [0.2609, 0.6348, 0.1194, 0.8101]],

        [[0.1463, 0.3807, 0.6052, 0.4311],
         [0.4888, 0.7776, 0.6835, 0.5198],
         [0.3531, 0.5815, 0.3338, 0.6531],
         [0.1442, 0.9355, 0.8658, 0.2634],
         [0.2609, 0.6348, 0.1194, 0.8101]]])


In [42]:
d = torch.bmm(a,c)
describe(d)

Type:torch.FloatTensor
Shape/Size: torch.Size([3, 4, 4])
Value: 
tensor([[[0.6627, 1.7497, 1.1145, 1.4499],
         [0.9190, 1.7675, 1.0309, 1.7196],
         [0.6251, 1.1701, 0.7590, 1.1741],
         [0.7554, 1.9156, 1.3836, 1.8741]],

        [[0.7965, 1.5696, 1.1391, 1.4849],
         [0.7219, 1.4980, 1.1355, 1.4250],
         [0.6236, 1.8316, 1.3509, 1.2610],
         [0.8582, 2.0494, 1.7203, 1.4904]],

        [[0.5256, 1.3800, 1.2936, 1.1303],
         [0.8945, 1.7693, 1.3953, 1.5025],
         [0.6382, 1.7929, 1.6678, 1.1804],
         [0.4338, 1.2747, 1.1233, 0.7264]]])
