<a href="https://colab.research.google.com/github/lizzylazy/NLP_pytorch/blob/main/Chapter1pytorch_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Connecting google drive

In [ ]:
from google.colab import drive
drive.mount('/content/gdrive')


Mounted at /content/gdrive


In [ ]:
% cd /content/gdrive/MyDrive/pytorch_NLP/

/content/gdrive/MyDrive/pytorch_NLP


In [ ]:
%ls 

 advancedDL/   ChemProtRE/  'Colab Notebooks'/   pytorch_NLP/


In [ ]:
pwd

'/content/gdrive'

# Create a tensor

In [ ]:
import torch

In [ ]:
# help function 
def describe(x):
  print('Type:{}'.format(x.type()))
  print('Shape/Size: {}'.format(x.shape))
  print('Value: \n{}'.format(x))

In [ ]:
describe(torch.Tensor(2,3))

Type:torch.FloatTensor
Shape/Size: torch.Size([2, 3])
Value: 
tensor([[-4.6750e+00,  3.0796e-41,  3.7835e-44],
        [ 0.0000e+00,         nan,  6.4460e-44]])


In [ ]:
describe(torch.rand(2,3))
describe(torch.randn(2,3))

Type:torch.FloatTensor
Shape/Size: torch.Size([2, 3])
Value: 
tensor([[ 0.2907, -0.7387, -1.2894],
        [-0.5255,  0.8750,  1.5888]])


In [ ]:
describe(torch.zeros(2,3))
describe(torch.ones(2,3))

Type:torch.FloatTensor
Shape/Size: torch.Size([2, 3])
Value: 
tensor([[0., 0., 0.],
        [0., 0., 0.]])
Type:torch.FloatTensor
Shape/Size: torch.Size([2, 3])
Value: 
tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [ ]:
x = torch.arange(6, dtype=float)

In [ ]:
describe(x)

Type:torch.DoubleTensor
Shape/Size: torch.Size([6])
Value: 
tensor([0., 1., 2., 3., 4., 5.], dtype=torch.float64)


In [ ]:
x = torch.FloatTensor(x)

In [ ]:
describe(x)

Type:torch.FloatTensor
Shape/Size: torch.Size([6])
Value: 
tensor([0., 1., 2., 3., 4., 5.])


In [ ]:
x = x.reshape(2,3)
describe(x)

Type:torch.FloatTensor
Shape/Size: torch.Size([2, 3])
Value: 
tensor([[0., 1., 2.],
        [3., 4., 5.]])


In [ ]:
describe(x.sum())
describe(x.sum(dim=0)) # sum along row
describe(x.sum(dim=1)) # sum along column

Type:torch.FloatTensor
Shape/Size: torch.Size([])
Value: 
15.0
Type:torch.FloatTensor
Shape/Size: torch.Size([3])
Value: 
tensor([3., 5., 7.])
Type:torch.FloatTensor
Shape/Size: torch.Size([2])
Value: 
tensor([ 3., 12.])


In [ ]:
describe(x.transpose(1,0))
describe(x.transpose(0,1))

Type:torch.FloatTensor
Shape/Size: torch.Size([3, 2])
Value: 
tensor([[0., 3.],
        [1., 4.],
        [2., 5.]])
Type:torch.FloatTensor
Shape/Size: torch.Size([3, 2])
Value: 
tensor([[0., 3.],
        [1., 4.],
        [2., 5.]])


In [ ]:
row_indices = torch.arange(2).long()
col_indices = torch.LongTensor([0, 1])
# describe(x[row_indices, col_indices])

In [ ]:
row_indices

tensor([0, 1])

In [ ]:
col_indices

tensor([0, 1])

In [ ]:
x[row_indices, col_indices]

tensor([0., 4.])

# Tensors and Computational Graphs


In [ ]:
import torch
x = torch.ones(2, 2, requires_grad=True)
describe(x)
print(x.grad is None)

Type:torch.FloatTensor
Shape/Size: torch.Size([2, 2])
Value: 
tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
True


In [ ]:
y = (x + 2) * (x + 5) + 3
describe(y)
print(x.grad is None)

Type:torch.FloatTensor
Shape/Size: torch.Size([2, 2])
Value: 
tensor([[21., 21.],
        [21., 21.]], grad_fn=<AddBackward0>)
True


In [ ]:
z = y.mean()
describe(z)
z.backward()
print(x.grad is None)

Type:torch.FloatTensor
Shape/Size: torch.Size([])
Value: 
21.0
False


# Exersice

1. Create a 2D tensor and then add a dimension of size 1 inserted at dimension 0

In [ ]:
x = torch.arange(6).view(2,3)
describe(x)

Type:torch.LongTensor
Shape/Size: torch.Size([2, 3])
Value: 
tensor([[0, 1, 2],
        [3, 4, 5]])


In [ ]:
y = x.unsqueeze(0)
describe(y)

Type:torch.LongTensor
Shape/Size: torch.Size([1, 2, 3])
Value: 
tensor([[[0, 1, 2],
         [3, 4, 5]]])


2. Remove the extra dimension you just added to the previous tensor.


In [ ]:
by.squeeze(0)


tensor([[0, 1, 2],
        [3, 4, 5]])

3. Create a random tensor of shape 5x3 in the interval [3, 7)

In [ ]:
a = torch.rand(5,3)
z= 3+a * 4

In [ ]:
describe(z)

Type:torch.FloatTensor
Shape/Size: torch.Size([5, 3])
Value: 
tensor([[3.7893, 6.5094, 4.6930],
        [4.9413, 3.5627, 4.4207],
        [3.7460, 4.0911, 4.3947],
        [6.1170, 6.0862, 3.0357],
        [4.3983, 4.3562, 5.4301]])


4. Create a tensor with values from a normal distribution (mean=0, std=1).


In [ ]:
torch.randn(2,3).normal_()


tensor([[ 1.7950,  1.2863,  0.5493],
        [ 0.8170, -0.2886, -0.4779]])

7. Return the batch matrix­matrix product of two three­dimensional matrices
(a=torch.rand(3,4,5), b=torch.rand(3,5,4)).

In [ ]:
a=torch.rand(3,4,5)
b=torch.rand(3,5,4)
c = torch.bmm(a,b)
describe(c)

Type:torch.FloatTensor
Shape/Size: torch.Size([3, 4, 4])
Value: 
tensor([[[1.6508, 1.4244, 1.5827, 1.3583],
         [1.8252, 1.7732, 1.5573, 1.7200],
         [0.8590, 0.7686, 0.7414, 0.7387],
         [1.4790, 2.0298, 1.8847, 1.2539]],

        [[1.5886, 1.7261, 1.8333, 1.9314],
         [0.6183, 0.7943, 0.6490, 0.8982],
         [1.0673, 1.0947, 0.9890, 1.0936],
         [1.1764, 1.1581, 1.4150, 1.3445]],

        [[0.6961, 1.0902, 1.0190, 1.3187],
         [1.3890, 1.4531, 1.6678, 2.4307],
         [0.6182, 0.7526, 0.9062, 1.1468],
         [1.5894, 1.5457, 1.8391, 2.2845]]])


8. Return the batch matrix­matrix product of a 3D matrix and a 2D matrix
(a=torch.rand(3,4,5), b=torch.rand(5,4))

In [ ]:
a=torch.rand(3,4,5)
b=torch.rand(5,4)

In [ ]:
c = b.unsqueeze(0).expand(a.size(0), *b.size())
describe(c)

Type:torch.FloatTensor
Shape/Size: torch.Size([3, 5, 4])
Value: 
tensor([[[0.4126, 0.2141, 0.4238, 0.4201],
         [0.0639, 0.8805, 0.9921, 0.8206],
         [0.2501, 0.0731, 0.4156, 0.7290],
         [0.8083, 0.4003, 0.9045, 0.7931],
         [0.4785, 0.0986, 0.0250, 0.9856]],

        [[0.4126, 0.2141, 0.4238, 0.4201],
         [0.0639, 0.8805, 0.9921, 0.8206],
         [0.2501, 0.0731, 0.4156, 0.7290],
         [0.8083, 0.4003, 0.9045, 0.7931],
         [0.4785, 0.0986, 0.0250, 0.9856]],

        [[0.4126, 0.2141, 0.4238, 0.4201],
         [0.0639, 0.8805, 0.9921, 0.8206],
         [0.2501, 0.0731, 0.4156, 0.7290],
         [0.8083, 0.4003, 0.9045, 0.7931],
         [0.4785, 0.0986, 0.0250, 0.9856]]])


In [ ]:
d = torch.bmm(a,c)
describe(d)

Type:torch.FloatTensor
Shape/Size: torch.Size([3, 4, 4])
Value: 
tensor([[[1.4767, 0.6940, 1.4417, 2.2454],
         [1.0562, 1.0687, 1.8439, 2.1757],
         [1.3042, 1.0558, 1.6839, 1.9635],
         [1.4037, 0.7214, 1.4157, 2.2118]],

        [[1.5852, 1.0953, 1.9907, 2.5865],
         [0.9370, 0.4537, 0.8081, 1.6062],
         [0.9306, 0.8863, 1.3850, 2.2533],
         [0.7050, 1.0690, 1.4437, 1.7243]],

        [[0.9855, 0.7516, 1.3585, 1.7242],
         [0.8977, 0.4442, 1.0317, 1.6004],
         [0.6362, 0.9309, 1.2765, 1.3932],
         [1.2394, 0.8377, 1.4308, 1.8949]]])
